### ISSUE TITLE
 syntax error, unexpected ':', expecting end-of-input

### ISSUE THREAD

**Issue by vikramvi** [burtlo/yard-cucumber#80]
gherkin (4.0.0, 2.12.2)
cucumber (2.4.0, 1.3.12)
yard (0.9.7, 0.9.5, 0.8.7.3)
yard-cucumber (3.1.0, 2.3.2)

After executing below command from mac OS X terminal

`yardoc '/Users/buildserver/Documents/BDDStories/Mobile/**/*.feature' '/Users/buildserver/Documents/BDDStories/Web/**/*.feature'`

For all the feature files I'm getting below error

```
[warn]: Syntax error in `/users/buildserver/documents/bddstories/web/loginpage/password_reset.feature`:(1,8): syntax error, unexpected ':', expecting end-of-input
[warn]: ParserSyntaxError: syntax error in `/Users/buildserver/Documents/BDDStories/Web/LoginPage/password_reset.feature`:(1,8): syntax error, unexpected ':', expecting end-of-input
[warn]: Stack trace:
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:583:in `on_parse_error'
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:442:in `parse'
	/Users/buildserver/.rvm/gems/ruby-2.4.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:46:in `block in parse'

```
Please clarify how to fix this

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
I could get this working with below versions

I had very hard time to get this fixed, can you update update README with dependancies' version

ruby 2.3.2p217 (2016-11-15 revision 56796)

Gemfile
source "https://rubygems.org"

gem 'redcarpet'
gem 'gherkin', '~> 4.0'

Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    gherkin (4.0.0)
    redcarpet (2.2.2)

PLATFORMS
  ruby

DEPENDENCIES
  gherkin (~> 4.0)
  redcarpet

BUNDLED WITH
   1.13.7

*** LOCAL GEMS ***

bigdecimal (default: 1.2.8)
builder (3.2.2)
bundler (1.13.7)
bundler-unload (1.0.2)
cucumber (2.4.0, 1.3.20)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
gherkin (4.0.0, 2.12.2)
io-console (default: 0.4.5)
json (default: 1.8.3)
minitest (5.8.5)
multi_json (1.12.1)
multi_test (0.1.2)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (default: 2.1.0)
rake (12.0.0, 10.4.2)
rdoc (default: 4.2.1)
redcarpet (3.4.0, 2.2.2)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.1.5)
yard (0.9.8)
yard-cucumber (3.1.0, 2.3.2)

**Comment by vikramvi** [comment]
config file entry under .yard.  

Absolutely don't have any idea which one of these steps has fixed the issue

--- !ruby/hash-with-ivars:SymbolHash
elements:
  :load_plugins: true
  :ignored_plugins: []
  :autoload_plugins: []
  :safe_mode: false
ivars:
  :@symbolize_value: false
