### ISSUE TITLE
Invalid configuration file error: uninitialized constant Cucumber::Gherkin::AstBuilder

### ISSUE THREAD

**Issue by bfaloona** [burtlo/yard-cucumber#92]
```$ rake spec
[error]: Invalid configuration file, using default options.
[error]: NameError: uninitialized constant Cucumber::Gherkin::AstBuilder
[error]: Stack trace:
	/.rvm/gems/ruby-2.4.3/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:3:in `<module:Parser>'
	/.rvm/gems/ruby-2.4.3/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:2:in `<module:Cucumber>'
	/.rvm/gems/ruby-2.4.3/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:1:in `<top (required)>'
	/.rvm/gems/ruby-2.4.3/gems/yard-cucumber-3.1.0/lib/yard-cucumber.rb:14:in `require'
	/.rvm/gems/ruby-2.4.3/gems/yard-cucumber-3.1.0/lib/yard-cucumber.rb:14:in `<top (required)>'
	/.rvm/gems/ruby-2.4.3/gems/yard-0.8.7.6/lib/yard/config.rb:161:in `require'

/.rvm/rubies/ruby-2.4.3/bin/ruby -I/.rvm/gems/ruby-2.4.3/gems/rspec-core-3.7.0/lib:/.rvm/gems/ruby-2.4.3/gems/rspec-support-3.7.0/lib /.rvm/gems/ruby-2.4.3/gems/rspec-core-3.7.0/exe/rspec --pattern ./spec/\*\*/\*_spec.rb```

Ruby:
`ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]`

Ruby Gems:
```PATH
  remote: .
  specs:
    indy (0.5.0)
      activesupport (~> 4.2.10)

GEM
  remote: http://rubygems.org/
  specs:
    activesupport (4.2.10)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    builder (3.2.3)
    coderay (1.1.2)
    concurrent-ruby (1.0.5)
    cucumber (2.4.0)
      builder (>= 2.1.2)
      cucumber-core (~> 1.5.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 4.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.5.0)
      gherkin (~> 4.0)
    cucumber-wire (0.0.1)
    diff-lcs (1.3)
    docile (1.1.5)
    ffi (1.9.18)
    flog (4.3.2)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.4)
    formatador (0.2.5)
    gherkin (4.1.3)
    growl (1.0.3)
    guard (2.14.1)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-cucumber (2.1.2)
      cucumber (~> 2.0)
      guard-compat (~> 1.0)
      nenv (~> 0.1)
    guard-rspec (1.2.2)
      guard (>= 1.1)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    json (1.8.6)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    lumberjack (1.0.12)
    method_source (0.9.0)
    minitest (5.10.3)
    multi_json (1.12.2)
    multi_test (0.1.2)
    nenv (0.3.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    rake (10.4.2)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.0)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-prof (0.0.7)
      rspec (~> 3.0)
      ruby-prof
    rspec-support (3.7.0)
    ruby-prof (0.13.1)
    ruby_dep (1.5.0)
    ruby_gntp (0.3.4)
    ruby_parser (3.10.1)
      sexp_processor (~> 4.9)
    sexp_processor (4.10.0)
    shellany (0.0.1)
    simplecov (0.11.2)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    thor (0.20.0)
    thread_safe (0.3.6)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    yard (0.8.7.6)
    yard-cucumber (3.1.0)
      cucumber (~> 2)
      gherkin (~> 4.0)
      yard (~> 0.8, >= 0.8.1)

PLATFORMS
  ruby

DEPENDENCIES
  cucumber (~> 2.4.0)
  flog (~> 4.3.0)
  growl (~> 1.0.0)
  guard (~> 2.14.1)
  guard-cucumber (~> 2.1.2)
  guard-rspec (~> 1.2.0)
  i18n (~> 0.7)
  indy!
  rake (~> 10.4.0)
  rb-fsevent (~> 0.9.0)
  rspec (~> 3.7.0)
  rspec-mocks (~> 3.7.0)
  rspec-prof (~> 0.0.0)
  ruby-prof (~> 0.13.0)
  ruby_gntp (~> 0.3.0)
  simplecov (~> 0.11.0)
  yard (~> 0.8.0)
  yard-cucumber (~> 3.1.0)

BUNDLED WITH
   1.16.1
```

**Comment by burtlo** [comment]
I cut a new release of `yard-cucumber` - 4.0.0. I think that addresses some the errors I was seeing when running `rake yard`. I didn't see the errors you were describing when running `rake spec`.

**Comment by weh** [comment]
looks like a duplicate of  #72
